openapi: 3.0.0
info:
  title: Expense Tracker API
  version: 1.0.0
paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User created
        "400":
          description: Invalid input
  /api/auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /api/expenses:
    get:
      summary: Get all expenses for the logged-in user
      responses:
        "200":
          description: A list of expenses
    post:
      summary: Create a new expense
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                amount:
                  type: number
                category:
                  type: string
                date:
                  type: string
                  format: date
      responses:
        "201":
          description: Expense created
        "400":
          description: Invalid input
